= About Me
Malte Dehling <mdehling@gmail.com>

:archive-pfx:   https://web.archive.org/web/20220601042136
:uni-math-hp:   {archive-pfx}/https://www.uni-math.gwdg.de/mdehling/

My name is Malte Dehling.  I was born in Boston, Massachusetts, but lived most
of my life in the Netherlands and Germany.  I have recently moved back to the
United States where I currently live in La Jolla, California.

I have a doctoral degree in mathematics from the University of Göttingen.  If
you're curious what sort of research I did, head over to my old
link:{uni-math-hp}[academic homepage] where I try to explain some of my work.

I've also been interested in coding and technology in general from a young
age.  I first learned to program in QBasic but quickly moved on to Turbo
Pascal with inline assembly for faster graphics.  These days my go to
languages are C, Python, and Lua, but I'm familiar with quite a few others and
generally love picking up new skills!  To see what I've been working on
recently, have a look at my link:/projects[projects] page.

When I'm not at my computer, I love to spend time outdoors, hiking, running,
or cycling.
