name: Middleman Build and Deploy Workflow

on:
  push:
    branches: ['main']

jobs:
  middleman-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'
      - name: Middleman Build and Deploy Step
        uses: './.github/actions/middleman-build-and-deploy'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
